print('II  |  I')
print('=========')
print('III | IV')
x = int(input('Введите координату X: '))
y = int(input('Введите координату Y: '))
if x == 0 or y == 0: print('Координаты не могут быть равны 0!')
elif x > 0 and y > 0: print('Точка находится в I четверти')
elif x > 0 and y < 0: print('Точка находится в IV четверти')
elif x < 0 and y > 0: print('Точка находится в II четверти')
elif x < 0 and y < 0: print('Точка находится в III четверти')